---
# tasks file for ansible-role-docker-container-watchtower

- name: docker_image pull {{ docker_image_watchtower_name }}
  community.docker.docker_image:
    name: '{{ docker_image_watchtower_name }}'
    source: pull
    # Select platform for pulling. If not specified, will pull whatever docker prefers.
    pull:
      platform: amd64
  when: 
    - docker_image_watchtower_pull is defined

- name: docker_network {{ docker_container_watchtower_name }}
  community.docker.docker_network:
    name: "{{ docker_network_watchtower_name }}"
    driver: "{{ docker_network_watchtower_driver | default('bridge') }}"
    attachable: "{{ docker_network_watchtower_attachable | default('yes') }}"
    enable_ipv6: "{{ docker_network_watchtower_enable_ipv6 | default('no') }}"
    internal: "{{ docker_network_watchtower_internal | default('no') }}"
    state: present


- name: docker_container {{ docker_container_watchtower_name }}
  community.docker.docker_container:
    name: "{{ docker_container_watchtower_name }}"
    image: "{{ docker_container_watchtower_image }}"
    state: "{{ docker_container_watchtower_state | default('started') }}"
    recreate: "{{ docker_container_watchtower_recreate | default('no') }}"
    restart: "{{ docker_container_watchtower_restart | default('no') }}"
    restart_policy: "{{ docker_container_watchtower_restart_policy | default('always') }}"
    container_default_behavior: no_defaults
    auto_remove: "{{ docker_container_watchtower_auto_remove | default('no') }}"
    detach: "{{ docker_container_watchtower_detach | default('yes') }}"
    init: "{{ docker_container_watchtower_init | default('no') }}"
    interactive: "{{ docker_container_watchtower_interactive | default('no') }}"
    keep_volumes: "{{ docker_container_watchtower_keep_volumes | default('yes') }}"
    memory: "{{ docker_container_watchtower_memory | default('0') }}"
    paused: "{{ docker_container_watchtower_paused | default('no') }}"
    privileged: "{{ docker_container_watchtower_privileged | default('no') }}"
    read_only: "{{ docker_container_watchtower_read_only | default('no') }}"
    tty: "{{ docker_container_watchtower_tty | default('no') }}"
    env_file: "{{ docker_container_watchtower_env_file | default(omit) }}"
    env: "{{ docker_container_watchtower_env | default(omit) }}"
    volumes: "{{ docker_container_watchtower_volumes | default(omit) }}"
    labels: "{{ docker_container_watchtower_labels | default(omit) }}"
    networks_cli_compatible: "{{ docker_container_watchtower_networks_cli_compatible | default('yes') }}"
    network_mode: "{{ docker_network_watchtower_name }}"
    pull: "{{ docker_container_watchtower_pull | default('no') }}"
    purge_networks: "{{ docker_container_watchtower_purge_networks | default('yes') }}"
    networks: "{{ docker_container_watchtower_networks }}"
    published_ports: "{{ docker_container_watchtower_ports | default(omit) }}"
